version: "3.9"
services:
  front:
    image: node
    volumes:
    - './registration-front:/registration-front'
    command: bash -c "cd ./registration-front && apt update && apt install && apt install yarn -y && yarn install && yarn dev --host 0.0.0.0"
    ports:
      - "5173:5173"
    expose:
      - "5173"