version: "3.9"
services:
  front:
    image: node
    volumes:
    - './packages/registration-front:/registration-front'
    command: bash -c "cd ./registration-front && apt update && apt install && apt install yarn -y && yarn install && yarn dev --host 0.0.0.0"
    ports:
      - "5173:5173"

  back:
    image: node
    volumes:
    - './packages/registration-back:/registration-back'
    command: bash -c "cd ./registration-back && apt update && apt install && apt install yarn -y && yarn install && yarn dev --host 0.0.0.0"
    ports:
      - "3333:3333"