version: "3.9"
services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "--password=${MYSQL_ROOT_PASSWORD}",
        ]
      timeout: 20s
      retries: 10
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_TCP_PORT= ${MYSQL_PORT}

  front:
    image: node
    volumes:
    - './packages/registration-front:/registration-front'
    command: bash -c "cd ./registration-front && apt update && apt install && apt install yarn -y && yarn install && yarn dev --host 0.0.0.0"
    ports:
      - "5173:5173"

  back:
    image: node
    depends_on:
      mysql: 
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - './packages/registration-back:/registration-back'
    command: bash -c "cd ./registration-back && apt update && apt install && apt install yarn -y && yarn install && yarn run migration:up && yarn dev --host 0.0.0.0" 
    ports:
      - "3333:3333"

