version: "3.9"
services:
  front:
    image: node
    volumes:
    - './packages/registration-front:/registration-front'
    command: bash -c "cd ./registration-front && apt update && apt install && apt install yarn -y && yarn install && yarn dev --host 0.0.0.0"
    ports:
      - "5173:5173"

  back:
    image: node
    env_file:
    - .env
    volumes:
    - './packages/registration-back:/registration-back'
    command: bash -c "cd ./registration-back && apt update && apt install && apt install yarn -y && yarn install && yarn dev --host 0.0.0.0"
    ports:
      - "3333:3333"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    hostname: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}